version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: grocery-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./GroceryBE
    container_name: grocery-backend
    ports:
      - "5000:5000"
    env_file:
      - ./GroceryAppBE-/.env
    depends_on:
      - mongo

  frontend:
    build: ./GroceryFE
    container_name: grocery-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:

