apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-backend
  template:
    metadata:
      labels:
        app: grocery-backend
    spec:
      containers:
        - name: backend
          image: mayurpandit25/grocery_backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/grocerydb
            - name: PORT
              value: "5000"

