apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-frontend
  template:
    metadata:
      labels:
        app: grocery-frontend
    spec:
      containers:
        - name: frontend
          image: mayurpandit25/grocery_frontend:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

